-- Phase 4F: one-occurrence client SKIP approval and controlled route replanning.

alter table app_private.outbox_events drop constraint outbox_events_producer_module_check;
alter table app_private.outbox_events add constraint outbox_events_producer_module_check check(producer_module in('identity-access','clients','service-addresses','service-configuration','geography','workforce','vehicles','daily-roster','routes','route-operations','vehicle-tracking','operational-issues','needs-attention','communications','integrations','configuration','reporting','audit','system-health','platform-runtime','operational-intelligence','website-intake','client-migration','accounting','financial-eligibility','client-skip'));

insert into app_private.permissions(permission_key,description) values
 ('client_skip.read','Read client SKIP requests within assigned regions'),
 ('client_skip.review','Qualify and rematch client SKIP requests'),
 ('client_skip.approve','Approve one-occurrence client SKIP exclusions'),
 ('client_skip.reject','Reject, expire, or deduplicate client SKIP requests'),
 ('client_skip.replan','Request controlled replanning after an approved SKIP')
on conflict do nothing;
insert into app_private.role_permissions(role_id,permission_key)
select r.role_id,p.permission_key from app_private.roles r cross join app_private.permissions p
where r.role_key in('director_admin','operations_manager') and p.permission_key like 'client_skip.%' on conflict do nothing;
insert into app_private.role_permissions(role_id,permission_key)
select r.role_id,p.permission_key from app_private.roles r cross join app_private.permissions p
where r.role_key='office_admin' and p.permission_key like 'client_skip.%' on conflict do nothing;
insert into app_private.role_permissions(role_id,permission_key)
select r.role_id,'routes.replan' from app_private.roles r where r.role_key='office_admin' on conflict do nothing;

insert into app_private.configuration_definitions(configuration_key,value_type,default_value,description,is_required) values
 ('client-skip.cutoff-policy','json','{"mode":"manual_review_after_publication","nearCutoffMinutes":120}'::jsonb,'Versioned cutoff posture; production timing requires approval.',false),
 ('client-skip.automatic-draft-replan','boolean','false','Automatic draft candidate generation remains disabled by default.',false)
on conflict(configuration_key) do nothing;

create table app_private.collection_occurrences(
 collection_occurrence_id uuid primary key default gen_random_uuid(), client_service_id uuid not null references app_private.client_services,
 service_date date not null, operational_day_id uuid references app_private.operational_days, service_region_id uuid not null references app_private.service_regions,
 expected_collection_day smallint not null check(expected_collection_day between 1 and 7), lifecycle_status text not null default 'expected'
  check(lifecycle_status in('expected','included','excluded','completed','not_serviced','cancelled','superseded')),
 source_configuration_id uuid not null references app_private.service_configurations, source_configuration_version text not null,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(client_service_id,service_date)
);
create index collection_occurrences_region_date_idx on app_private.collection_occurrences(service_region_id,service_date,lifecycle_status);

create table app_private.client_skip_requests(
 client_skip_request_id uuid primary key default gen_random_uuid(), inbound_message_id uuid not null references app_private.inbound_messages,
 client_id uuid references app_private.clients, client_contact_id uuid references app_private.client_contacts,
 client_service_id uuid references app_private.client_services, collection_occurrence_id uuid references app_private.collection_occurrences,
 service_region_id uuid references app_private.service_regions, requested_at timestamptz not null, channel text not null,
 normalized_command text not null check(normalized_command='skip'), match_state text not null
  check(match_state in('matched','ambiguous_service','no_active_service','ambiguous_occurrence','no_upcoming_occurrence')),
 lifecycle_status text not null default 'received' check(lifecycle_status in('received','matching','needs_review','qualified','approved','rejected','applied','acknowledged','failed','expired','duplicate')),
 cutoff_status text not null default 'before_cutoff' check(cutoff_status in('before_cutoff','near_cutoff','after_cutoff','unknown')),
 review_version integer not null default 1, reviewed_by uuid references auth.users, reviewed_at timestamptz,
 rejection_reason text, approval_context text, route_impact_snapshot jsonb, resulting_exclusion_id uuid,
 acknowledgement_intent_id uuid references app_private.communication_intents, duplicate_of_request_id uuid references app_private.client_skip_requests,
 correlation_id uuid not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(inbound_message_id)
);
create index client_skip_queue_idx on app_private.client_skip_requests(service_region_id,lifecycle_status,requested_at);
create unique index client_skip_one_active_request_per_occurrence on app_private.client_skip_requests(collection_occurrence_id)
 where lifecycle_status in('qualified','approved','applied','acknowledged');

create table app_private.collection_occurrence_exclusions(
 collection_occurrence_exclusion_id uuid primary key default gen_random_uuid(), collection_occurrence_id uuid not null references app_private.collection_occurrences,
 client_service_id uuid not null references app_private.client_services, effective_service_date date not null,
 reason_code text not null check(reason_code='client_requested_skip'), source_skip_request_id uuid not null references app_private.client_skip_requests,
 lifecycle_status text not null default 'active' check(lifecycle_status in('active','cancelled','superseded')),
 created_by uuid not null references auth.users, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create unique index occurrence_one_active_skip_exclusion on app_private.collection_occurrence_exclusions(collection_occurrence_id) where lifecycle_status='active';
alter table app_private.client_skip_requests add constraint client_skip_resulting_exclusion_fk foreign key(resulting_exclusion_id) references app_private.collection_occurrence_exclusions;

create table app_private.client_skip_replan_requests(
 client_skip_replan_request_id uuid primary key default gen_random_uuid(), client_skip_request_id uuid not null references app_private.client_skip_requests,
 source_route_version_id uuid references app_private.route_versions, candidate_route_version_id uuid references app_private.route_versions,
 lifecycle_status text not null default 'pending' check(lifecycle_status in('pending','running','succeeded','failed','cancelled')),
 requested_by uuid not null references auth.users, reason text not null, correlation_id uuid not null,
 requested_at timestamptz not null default now(), completed_at timestamptz, failure_code text, unique(client_skip_request_id,source_route_version_id)
);

alter table app_private.collection_occurrences enable row level security;
alter table app_private.client_skip_requests enable row level security;
alter table app_private.collection_occurrence_exclusions enable row level security;
alter table app_private.client_skip_replan_requests enable row level security;
revoke all on app_private.collection_occurrences,app_private.client_skip_requests,app_private.collection_occurrence_exclusions,app_private.client_skip_replan_requests from public,anon,authenticated;
grant select,insert,update,delete on app_private.collection_occurrences,app_private.client_skip_requests,app_private.collection_occurrence_exclusions,app_private.client_skip_replan_requests to service_role;

alter table app_private.unassigned_route_services drop constraint unassigned_route_services_reason_code_check;
alter table app_private.unassigned_route_services add constraint unassigned_route_services_reason_code_check check(reason_code in
 ('missing_coordinates','missing_territory','no_eligible_team','capacity_exceeded','working_window_exceeded','invalid_service_configuration','unsupported_cadence','roster_assignment_unavailable','financial_hold','client_requested_skip'));

create or replace function app_private.require_client_skip_access(p_actor uuid,p_permission text,p_region uuid) returns void language plpgsql security definer set search_path='' as $$begin
 if p_region is null or not app_private.user_has_region_permission(p_actor,p_permission,p_region) then raise exception 'region_denied' using errcode='42501';end if;end$$;
create or replace function app_private.client_skip_has_permission(p_actor uuid,p_permission text)returns boolean language sql stable security definer set search_path='' as $$select exists(select 1 from public.user_profiles profile join app_private.user_roles ur on ur.user_id=profile.user_id join app_private.role_permissions rp on rp.role_id=ur.role_id where profile.user_id=p_actor and profile.is_active and rp.permission_key=p_permission)$$;

create or replace function app_private.client_skip_route_impact(p_occurrence uuid) returns jsonb language sql stable security definer set search_path='' as $$
select jsonb_build_object('routeVersions',coalesce((select jsonb_agg(jsonb_build_object('routeVersionId',v.route_version_id,'routePlanId',p.route_plan_id,'status',v.version_status,'isStale',v.is_stale)) from app_private.collection_occurrences o join app_private.route_plans p on p.operational_day_id=o.operational_day_id join app_private.route_versions v on v.route_plan_id=p.route_plan_id join app_private.planned_route_stops s on s.route_version_id=v.route_version_id and s.client_service_id=o.client_service_id where o.collection_occurrence_id=p_occurrence),'[]'::jsonb),
'routeOperations',coalesce((select jsonb_agg(jsonb_build_object('routeOperationId',ro.route_operation_id,'status',ro.lifecycle_status,'manifestRevision',ro.manifest_revision)) from app_private.collection_occurrences o join app_private.route_operations ro on ro.operational_day_id=o.operational_day_id join app_private.route_operation_stops ros on ros.route_operation_id=ro.route_operation_id join app_private.planned_route_stops source_stop on source_stop.planned_route_stop_id=ros.source_planned_route_stop_id and source_stop.client_service_id=o.client_service_id where o.collection_occurrence_id=p_occurrence),'[]'::jsonb))$$;

create or replace function api.client_skip_consume_inbound(p_inbound_message_id uuid,p_correlation_id uuid) returns jsonb language plpgsql security definer set search_path='' as $$declare
 m app_private.inbound_messages%rowtype;r app_private.client_skip_requests%rowtype;svc record;svc_count integer;next_date date;occ app_private.collection_occurrences%rowtype;active_request uuid;local_date date;
begin select * into m from app_private.inbound_messages where inbound_message_id=p_inbound_message_id for update;
 if m.inbound_message_id is null then raise exception 'not_found' using errcode='P0002';end if;
 if m.recognized_command<>'skip' then raise exception 'not_skip_command' using errcode='22023';end if;
 select * into r from app_private.client_skip_requests where inbound_message_id=m.inbound_message_id;if r.client_skip_request_id is not null then return to_jsonb(r);end if;
 if m.match_classification<>'matched' or m.matched_client_id is null then
  insert into app_private.client_skip_requests(inbound_message_id,client_id,client_contact_id,service_region_id,requested_at,channel,normalized_command,match_state,lifecycle_status,cutoff_status,correlation_id)
  values(m.inbound_message_id,m.matched_client_id,m.matched_contact_id,m.service_region_id,m.received_at,m.channel,'skip','ambiguous_service','needs_review','unknown',p_correlation_id)returning * into r;
 else
  select count(*) into svc_count from app_private.client_services cs where cs.client_id=m.matched_client_id and cs.lifecycle_status='active';
  if svc_count=1 then
   select cs.client_service_id,sc.service_configuration_id,sc.service_region_id,sc.configured_collection_day,sc.effective_from,sc.updated_at
   into svc from app_private.client_services cs join lateral(select * from app_private.service_configurations x where x.client_service_id=cs.client_service_id and x.effective_to is null order by x.effective_from desc limit 1)sc on true
   where cs.client_id=m.matched_client_id and cs.lifecycle_status='active';
   local_date:=(m.received_at at time zone coalesce((select timezone from app_private.operational_days where service_region_id=svc.service_region_id and service_date>=m.received_at::date order by service_date limit 1),'Africa/Johannesburg'))::date;
   next_date:=local_date+mod(svc.configured_collection_day-extract(isodow from local_date)::integer+7,7);
   if next_date<svc.effective_from then next_date:=svc.effective_from+mod(svc.configured_collection_day-extract(isodow from svc.effective_from)::integer+7,7);end if;
   insert into app_private.collection_occurrences(client_service_id,service_date,operational_day_id,service_region_id,expected_collection_day,source_configuration_id,source_configuration_version)
   values(svc.client_service_id,next_date,(select operational_day_id from app_private.operational_days where service_region_id=svc.service_region_id and service_date=next_date),svc.service_region_id,svc.configured_collection_day,svc.service_configuration_id,svc.updated_at::text)
   on conflict(client_service_id,service_date)do update set client_service_id=excluded.client_service_id returning * into occ;
   select client_skip_request_id into active_request from app_private.client_skip_requests where collection_occurrence_id=occ.collection_occurrence_id and lifecycle_status in('qualified','approved','applied','acknowledged') limit 1;
   insert into app_private.client_skip_requests(inbound_message_id,client_id,client_contact_id,client_service_id,collection_occurrence_id,service_region_id,requested_at,channel,normalized_command,match_state,lifecycle_status,cutoff_status,duplicate_of_request_id,correlation_id)
   values(m.inbound_message_id,m.matched_client_id,m.matched_contact_id,svc.client_service_id,occ.collection_occurrence_id,svc.service_region_id,m.received_at,m.channel,'skip','matched',case when active_request is null then'qualified'else'duplicate'end,
   case when exists(select 1 from app_private.route_operations ro where ro.operational_day_id=occ.operational_day_id and ro.lifecycle_status in('accepted','in_progress','suspended','completed'))then'after_cutoff'when exists(select 1 from app_private.route_versions v join app_private.route_plans p using(route_plan_id)where p.operational_day_id=occ.operational_day_id and v.version_status='published')then'near_cutoff'else'before_cutoff'end,active_request,p_correlation_id)returning * into r;
  else
   insert into app_private.client_skip_requests(inbound_message_id,client_id,client_contact_id,requested_at,channel,normalized_command,match_state,lifecycle_status,cutoff_status,correlation_id)
   values(m.inbound_message_id,m.matched_client_id,m.matched_contact_id,m.received_at,m.channel,'skip',case when svc_count=0 then'no_active_service'else'ambiguous_service'end,'needs_review','unknown',p_correlation_id)returning * into r;
  end if;
 end if;
 insert into app_private.outbox_events(producer_module,event_name,event_version,aggregate_type,aggregate_id,payload,correlation_id,actor_kind,actor_id,occurred_at)values('client-skip','ClientSkip.RequestQualified',1,'client-skip-request',r.client_skip_request_id,jsonb_build_object('requestId',r.client_skip_request_id,'status',r.lifecycle_status,'regionId',r.service_region_id),p_correlation_id,'system','client-skip-command-consumer',now());
 return to_jsonb(r)||jsonb_build_object('routeImpact',case when r.collection_occurrence_id is null then null else app_private.client_skip_route_impact(r.collection_occurrence_id)end);end$$;

create or replace function api.client_skip_list(p_actor uuid,p_query jsonb default '{}')returns jsonb language plpgsql security definer set search_path='' as $$begin
 if not app_private.client_skip_has_permission(p_actor,'client_skip.read')then raise exception 'permission_denied' using errcode='42501';end if;
 return jsonb_build_object('items',(select coalesce(jsonb_agg(jsonb_build_object('requestId',r.client_skip_request_id,'clientId',r.client_id,'clientName',c.display_name,'clientServiceId',r.client_service_id,'serviceAddress',sa.address_line_1,'collectionDate',o.service_date,'receivedAt',r.requested_at,'channel',r.channel,'matchState',r.match_state,'status',r.lifecycle_status,'cutoffStatus',r.cutoff_status,'reviewVersion',r.review_version,'acknowledgementIntentId',r.acknowledgement_intent_id,'routeImpact',case when o.collection_occurrence_id is null then null else app_private.client_skip_route_impact(o.collection_occurrence_id)end)order by r.requested_at desc),'[]'::jsonb)from app_private.client_skip_requests r left join app_private.clients c on c.client_id=r.client_id left join app_private.collection_occurrences o on o.collection_occurrence_id=r.collection_occurrence_id left join app_private.client_services cs on cs.client_service_id=r.client_service_id left join app_private.service_addresses sa on sa.service_address_id=cs.service_address_id where r.service_region_id is not null and app_private.user_has_region_permission(p_actor,'client_skip.read',r.service_region_id) and(nullif(p_query->>'status','')is null or r.lifecycle_status=p_query->>'status')));end$$;

create or replace function api.client_skip_get(p_actor uuid,p_request uuid)returns jsonb language plpgsql security definer set search_path='' as $$declare r app_private.client_skip_requests%rowtype;begin select * into r from app_private.client_skip_requests where client_skip_request_id=p_request;if r.client_skip_request_id is null then raise exception 'not_found' using errcode='P0002';end if;perform app_private.require_client_skip_access(p_actor,'client_skip.read',r.service_region_id);return to_jsonb(r)||jsonb_build_object('routeImpact',case when r.collection_occurrence_id is null then null else app_private.client_skip_route_impact(r.collection_occurrence_id)end);end$$;

create or replace function api.client_skip_rematch(p_actor uuid,p_request uuid,p_service uuid,p_occurrence_date date,p_expected_version integer,p_reason text,p_correlation uuid)returns jsonb language plpgsql security definer set search_path='' as $$declare r app_private.client_skip_requests%rowtype;sc record;o app_private.collection_occurrences%rowtype;begin
 select * into r from app_private.client_skip_requests where client_skip_request_id=p_request for update;perform app_private.require_client_skip_access(p_actor,'client_skip.review',r.service_region_id);if r.review_version<>p_expected_version then raise exception 'stale_review' using errcode='40001';end if;if nullif(btrim(p_reason),'')is null then raise exception 'reason_required' using errcode='22023';end if;
 select * into sc from app_private.service_configurations where client_service_id=p_service and effective_from<=p_occurrence_date and(effective_to is null or effective_to>=p_occurrence_date)order by effective_from desc limit 1;if sc.service_configuration_id is null then raise exception 'ineligible_service' using errcode='22023';end if;perform app_private.require_client_skip_access(p_actor,'client_skip.review',sc.service_region_id);
 insert into app_private.collection_occurrences(client_service_id,service_date,operational_day_id,service_region_id,expected_collection_day,source_configuration_id,source_configuration_version)values(p_service,p_occurrence_date,(select operational_day_id from app_private.operational_days where service_region_id=sc.service_region_id and service_date=p_occurrence_date),sc.service_region_id,sc.configured_collection_day,sc.service_configuration_id,sc.updated_at::text)on conflict(client_service_id,service_date)do update set client_service_id=excluded.client_service_id returning * into o;
 update app_private.client_skip_requests set client_service_id=p_service,collection_occurrence_id=o.collection_occurrence_id,service_region_id=sc.service_region_id,match_state='matched',lifecycle_status='qualified',review_version=review_version+1,reviewed_by=p_actor,reviewed_at=now(),updated_at=now()where client_skip_request_id=p_request returning * into r;
 insert into app_private.business_audit_facts(action_key,actor_id,module_key,target_type,target_id,correlation_id,after_state)values('client_skip.rematched',p_actor,'client-skip','client-skip-request',p_request,p_correlation,jsonb_build_object('clientServiceId',p_service,'occurrenceId',o.collection_occurrence_id,'reason',p_reason));return to_jsonb(r);end$$;

create or replace function api.client_skip_approve(p_actor uuid,p_request uuid,p_expected_version integer,p_reason text,p_correlation uuid)returns jsonb language plpgsql security definer set search_path='' as $$declare r app_private.client_skip_requests%rowtype;e app_private.collection_occurrence_exclusions%rowtype;impact jsonb;client_name text;intent jsonb;op record;begin
 select * into r from app_private.client_skip_requests where client_skip_request_id=p_request for update;if r.client_skip_request_id is null then raise exception 'not_found' using errcode='P0002';end if;perform app_private.require_client_skip_access(p_actor,'client_skip.approve',r.service_region_id);if r.review_version<>p_expected_version then raise exception 'stale_review' using errcode='40001';end if;if r.lifecycle_status not in('qualified','needs_review')or r.collection_occurrence_id is null then raise exception 'request_not_qualified' using errcode='55000';end if;
 impact:=app_private.client_skip_route_impact(r.collection_occurrence_id);insert into app_private.collection_occurrence_exclusions(collection_occurrence_id,client_service_id,effective_service_date,reason_code,source_skip_request_id,created_by)select r.collection_occurrence_id,r.client_service_id,o.service_date,'client_requested_skip',r.client_skip_request_id,p_actor from app_private.collection_occurrences o where o.collection_occurrence_id=r.collection_occurrence_id on conflict(collection_occurrence_id)where lifecycle_status='active'do update set updated_at=now()returning * into e;
 update app_private.collection_occurrences set lifecycle_status='excluded',updated_at=now()where collection_occurrence_id=r.collection_occurrence_id;
 update app_private.route_versions v set is_stale=true,stale_reason='client_requested_skip',version_status=case when v.version_status='ready'then'draft'else v.version_status end,updated_at=now()from app_private.route_plans p,app_private.planned_route_stops s,app_private.collection_occurrences o where p.route_plan_id=v.route_plan_id and s.route_version_id=v.route_version_id and o.collection_occurrence_id=r.collection_occurrence_id and p.operational_day_id=o.operational_day_id and s.client_service_id=r.client_service_id and v.version_status in('draft','ready');
 select display_name into client_name from app_private.clients where client_id=r.client_id;
 intent:=api.communication_create_intent(p_actor,jsonb_build_object('communicationType','general_service_notice','clientId',r.client_id,'clientServiceId',r.client_service_id,'sourceDomain','client-skip','sourceReference',r.client_skip_request_id,'templateKey','skip_approved','templateVersion',1,'priority','normal','variables',jsonb_build_object('clientName',client_name,'collectionDate',(select service_date from app_private.collection_occurrences where collection_occurrence_id=r.collection_occurrence_id)::text)),p_correlation,'skip-approved-v'||p_expected_version);
 update app_private.client_skip_requests set lifecycle_status='applied',review_version=review_version+1,reviewed_by=p_actor,reviewed_at=now(),approval_context=p_reason,route_impact_snapshot=impact,resulting_exclusion_id=e.collection_occurrence_exclusion_id,acknowledgement_intent_id=(intent->>'communication_intent_id')::uuid,updated_at=now()where client_skip_request_id=p_request returning * into r;
 update app_private.inbound_messages set processing_status='processed'where inbound_message_id=r.inbound_message_id;
 for op in select ro.* from app_private.route_operations ro join app_private.collection_occurrences o on o.operational_day_id=ro.operational_day_id join app_private.route_operation_stops s on s.route_operation_id=ro.route_operation_id join app_private.planned_route_stops source_stop on source_stop.planned_route_stop_id=s.source_planned_route_stop_id and source_stop.client_service_id=r.client_service_id where o.collection_occurrence_id=r.collection_occurrence_id and ro.lifecycle_status in('accepted','in_progress','suspended')loop perform app_private.apply_operational_signal(jsonb_build_object('factType','route_deviation','vehicleId',op.current_vehicle_id,'routeOperationId',op.route_operation_id,'serviceRegionId',r.service_region_id,'detectedAt',now(),'evidenceFrom',now(),'evidenceTo',now(),'confidence','high','severity','warning','deduplicationKey','client-skip:'||r.client_skip_request_id||':active-operation','ruleVersion','phase-4f-v1','summary','Approved client SKIP requires operational review','evidence',jsonb_build_object('clientSkipRequestId',r.client_skip_request_id)),p_correlation);end loop;
 insert into app_private.business_audit_facts(action_key,actor_id,module_key,target_type,target_id,correlation_id,after_state)values('client_skip.approved',p_actor,'client-skip','client-skip-request',p_request,p_correlation,jsonb_build_object('occurrenceId',r.collection_occurrence_id,'exclusionId',e.collection_occurrence_exclusion_id));
 insert into app_private.outbox_events(producer_module,event_name,event_version,aggregate_type,aggregate_id,payload,correlation_id,actor_kind,actor_id,occurred_at)values('client-skip','ClientSkip.Approved',1,'client-skip-request',p_request,jsonb_build_object('requestId',p_request,'occurrenceId',r.collection_occurrence_id,'regionId',r.service_region_id),p_correlation,'user',p_actor::text,now()),('client-skip','ClientSkip.ExclusionApplied',1,'collection-occurrence',r.collection_occurrence_id,jsonb_build_object('requestId',p_request,'occurrenceId',r.collection_occurrence_id,'reason','client_requested_skip'),p_correlation,'user',p_actor::text,now());return to_jsonb(r)||jsonb_build_object('routeImpact',impact);end$$;

create or replace function api.client_skip_reject(p_actor uuid,p_request uuid,p_expected_version integer,p_action text,p_reason text,p_correlation uuid)returns jsonb language plpgsql security definer set search_path='' as $$declare r app_private.client_skip_requests%rowtype;client_name text;intent jsonb;target text;begin
 select * into r from app_private.client_skip_requests where client_skip_request_id=p_request for update;perform app_private.require_client_skip_access(p_actor,'client_skip.reject',r.service_region_id);if r.review_version<>p_expected_version then raise exception 'stale_review' using errcode='40001';end if;if p_action not in('rejected','expired','duplicate')then raise exception 'invalid_action' using errcode='22023';end if;if nullif(btrim(p_reason),'')is null then raise exception 'reason_required' using errcode='22023';end if;target:=p_action;
 if p_action='rejected'then select display_name into client_name from app_private.clients where client_id=r.client_id;intent:=api.communication_create_intent(p_actor,jsonb_build_object('communicationType','general_service_notice','clientId',r.client_id,'clientServiceId',r.client_service_id,'sourceDomain','client-skip','sourceReference',r.client_skip_request_id,'templateKey','skip_rejected','templateVersion',1,'priority','normal','variables',jsonb_build_object('clientName',client_name)),p_correlation,'skip-rejected-v'||p_expected_version);end if;
 update app_private.client_skip_requests set lifecycle_status=target,review_version=review_version+1,reviewed_by=p_actor,reviewed_at=now(),rejection_reason=p_reason,acknowledgement_intent_id=case when intent is null then acknowledgement_intent_id else(intent->>'communication_intent_id')::uuid end,updated_at=now()where client_skip_request_id=p_request returning * into r;
 insert into app_private.business_audit_facts(action_key,actor_id,module_key,target_type,target_id,correlation_id,after_state)values('client_skip.'||p_action,p_actor,'client-skip','client-skip-request',p_request,p_correlation,jsonb_build_object('reason',p_reason));insert into app_private.outbox_events(producer_module,event_name,event_version,aggregate_type,aggregate_id,payload,correlation_id,actor_kind,actor_id,occurred_at)values('client-skip',case when p_action='rejected'then'ClientSkip.Rejected'else'ClientSkip.RequestReviewed'end,1,'client-skip-request',p_request,jsonb_build_object('requestId',p_request,'status',p_action),p_correlation,'user',p_actor::text,now());return to_jsonb(r);end$$;

create or replace function api.client_skip_route_impact(p_actor uuid,p_request uuid)returns jsonb language plpgsql security definer set search_path='' as $$declare r app_private.client_skip_requests%rowtype;begin select * into r from app_private.client_skip_requests where client_skip_request_id=p_request;if r.client_skip_request_id is null then raise exception 'not_found' using errcode='P0002';end if;perform app_private.require_client_skip_access(p_actor,'client_skip.read',r.service_region_id);return app_private.client_skip_route_impact(r.collection_occurrence_id);end$$;

create or replace function api.client_skip_replan(p_actor uuid,p_request uuid,p_reason text,p_correlation uuid)returns jsonb language plpgsql security definer set search_path='' as $$declare r app_private.client_skip_requests%rowtype;o app_private.collection_occurrences%rowtype;source uuid;job app_private.client_skip_replan_requests%rowtype;candidate jsonb;begin
 select * into r from app_private.client_skip_requests where client_skip_request_id=p_request;perform app_private.require_client_skip_access(p_actor,'client_skip.replan',r.service_region_id);if r.lifecycle_status not in('applied','acknowledged')then raise exception 'exclusion_required' using errcode='55000';end if;if nullif(btrim(p_reason),'')is null then raise exception 'reason_required' using errcode='22023';end if;select * into o from app_private.collection_occurrences where collection_occurrence_id=r.collection_occurrence_id;if o.operational_day_id is null then raise exception 'operational_day_required' using errcode='55000';end if;select coalesce(p.current_version_id,p.current_published_version_id)into source from app_private.route_plans p where p.operational_day_id=o.operational_day_id;
 insert into app_private.client_skip_replan_requests(client_skip_request_id,source_route_version_id,requested_by,reason,correlation_id,lifecycle_status)values(p_request,source,p_actor,p_reason,p_correlation,'running')on conflict(client_skip_request_id,source_route_version_id)do update set client_skip_request_id=excluded.client_skip_request_id returning * into job;if job.lifecycle_status='succeeded'then return to_jsonb(job);end if;
 candidate:=api.route_generate(p_actor,o.operational_day_id,p_correlation,true,source,'client_requested_skip:'||p_request);update app_private.client_skip_replan_requests set lifecycle_status='succeeded',candidate_route_version_id=(candidate->>'route_version_id')::uuid,completed_at=now()where client_skip_replan_request_id=job.client_skip_replan_request_id returning * into job;
 insert into app_private.business_audit_facts(action_key,actor_id,module_key,target_type,target_id,correlation_id,after_state)values('client_skip.replan_requested',p_actor,'client-skip','client-skip-request',p_request,p_correlation,jsonb_build_object('sourceVersionId',source,'candidateVersionId',job.candidate_route_version_id));insert into app_private.outbox_events(producer_module,event_name,event_version,aggregate_type,aggregate_id,payload,correlation_id,actor_kind,actor_id,occurred_at)values('client-skip','ClientSkip.ReplanRequested',1,'client-skip-request',p_request,jsonb_build_object('requestId',p_request,'sourceVersionId',source,'candidateVersionId',job.candidate_route_version_id),p_correlation,'user',p_actor::text,now());return to_jsonb(job)||jsonb_build_object('candidate',candidate);end$$;

create or replace function api.client_skip_history(p_actor uuid,p_client_service uuid)returns jsonb language plpgsql security definer set search_path='' as $$declare region uuid;begin select service_region_id into region from app_private.service_configurations where client_service_id=p_client_service and effective_to is null order by effective_from desc limit 1;perform app_private.require_client_skip_access(p_actor,'client_skip.read',region);return jsonb_build_object('items',(select coalesce(jsonb_agg(jsonb_build_object('requestId',r.client_skip_request_id,'requestedAt',r.requested_at,'collectionDate',o.service_date,'status',r.lifecycle_status,'acknowledgementIntentId',r.acknowledgement_intent_id)order by r.requested_at desc),'[]'::jsonb)from app_private.client_skip_requests r left join app_private.collection_occurrences o using(collection_occurrence_id)where r.client_service_id=p_client_service));end$$;

create or replace function app_private.prevent_excluded_occurrence_stop()returns trigger language plpgsql security definer set search_path='' as $$declare occurrence uuid;begin select o.collection_occurrence_id into occurrence from app_private.route_versions v join app_private.route_plans p using(route_plan_id)join app_private.operational_days d using(operational_day_id)join app_private.collection_occurrences o on o.client_service_id=new.client_service_id and o.service_date=d.service_date join app_private.collection_occurrence_exclusions e on e.collection_occurrence_id=o.collection_occurrence_id and e.lifecycle_status='active'where v.route_version_id=new.route_version_id;if occurrence is null then return new;end if;insert into app_private.unassigned_route_services(route_version_id,client_service_id,service_configuration_id,service_address_id,reason_code,constraint_detail,remediation,service_snapshot)values(new.route_version_id,new.client_service_id,new.service_configuration_id,new.service_address_id,'client_requested_skip',jsonb_build_object('occurrenceId',occurrence),'Review the approved one-occurrence SKIP exclusion.',jsonb_build_object('occurrenceId',occurrence))on conflict(route_version_id,client_service_id)do nothing;return null;end$$;
create trigger planned_stop_skip_exclusion before insert on app_private.planned_route_stops for each row execute function app_private.prevent_excluded_occurrence_stop();
create or replace function app_private.recalculate_planned_route_totals()returns trigger language plpgsql security definer set search_path='' as $$begin new.planned_capacity_units:=(select coalesce(sum(drum_units),0)from app_private.planned_route_stops where planned_route_id=new.planned_route_id);new.planned_duration_minutes:=(select coalesce(sum(planned_duration_minutes+5),0)from app_private.planned_route_stops where planned_route_id=new.planned_route_id);return new;end$$;
create trigger planned_route_recalculate before update of planned_capacity_units,planned_duration_minutes on app_private.planned_routes for each row execute function app_private.recalculate_planned_route_totals();

insert into app_private.communication_templates(template_key,channel,communication_type,language,version,subject_template,body_template,variables_schema,lifecycle_status,approved_at) values
 ('skip_approved','whatsapp','general_service_notice','english',1,null,'Hello {{clientName}}. Your MegaBin collection for {{collectionDate}} has been skipped as requested.','["clientName","collectionDate"]'::jsonb,'active',now()),
 ('skip_approved','sms','general_service_notice','english',1,null,'Hello {{clientName}}. Your MegaBin collection for {{collectionDate}} has been skipped as requested.','["clientName","collectionDate"]'::jsonb,'active',now()),
 ('skip_approved','email','general_service_notice','english',1,'MegaBin collection SKIP confirmed','Hello {{clientName}}. Your MegaBin collection for {{collectionDate}} has been skipped as requested.','["clientName","collectionDate"]'::jsonb,'active',now()),
 ('skip_rejected','whatsapp','general_service_notice','english',1,null,'Hello {{clientName}}. We could not apply your MegaBin SKIP request. Our Office team can assist.','["clientName"]'::jsonb,'active',now()),
 ('skip_rejected','sms','general_service_notice','english',1,null,'Hello {{clientName}}. We could not apply your MegaBin SKIP request. Our Office team can assist.','["clientName"]'::jsonb,'active',now()),
 ('skip_rejected','email','general_service_notice','english',1,'MegaBin SKIP request update','Hello {{clientName}}. We could not apply your MegaBin SKIP request. Our Office team can assist.','["clientName"]'::jsonb,'active',now())on conflict do nothing;

revoke all on function api.client_skip_consume_inbound(uuid,uuid),api.client_skip_list(uuid,jsonb),api.client_skip_get(uuid,uuid),api.client_skip_rematch(uuid,uuid,uuid,date,integer,text,uuid),api.client_skip_approve(uuid,uuid,integer,text,uuid),api.client_skip_reject(uuid,uuid,integer,text,text,uuid),api.client_skip_route_impact(uuid,uuid),api.client_skip_replan(uuid,uuid,text,uuid),api.client_skip_history(uuid,uuid)from public,anon,authenticated;
grant execute on function api.client_skip_consume_inbound(uuid,uuid),api.client_skip_list(uuid,jsonb),api.client_skip_get(uuid,uuid),api.client_skip_rematch(uuid,uuid,uuid,date,integer,text,uuid),api.client_skip_approve(uuid,uuid,integer,text,uuid),api.client_skip_reject(uuid,uuid,integer,text,text,uuid),api.client_skip_route_impact(uuid,uuid),api.client_skip_replan(uuid,uuid,text,uuid),api.client_skip_history(uuid,uuid)to service_role;
