-- Phase 2B: provider-neutral route refinement and optimization attempts.
insert into app_private.permissions(permission_key,description) values
 ('routes.optimize','Request route optimization within assigned regions'),
 ('routes.optimization.read','Read optimization attempts and comparisons'),
 ('routes.optimization.apply','Accept or reject optimization candidates') on conflict do nothing;
insert into app_private.role_permissions(role_id,permission_key) select r.role_id,p.permission_key from app_private.roles r cross join app_private.permissions p where r.role_key in ('director_admin','operations_manager','office_admin') and p.permission_key in ('routes.optimize','routes.optimization.read','routes.optimization.apply') on conflict do nothing;

insert into app_private.configuration_definitions(configuration_key,description,value_type,is_required,default_value) values
 ('routes.routing-provider','Active provider-neutral routing adapter key','string',true,'"fake-routing"'),
 ('routes.optimization-provider','Active provider-neutral optimization adapter key','string',true,'"fake-optimizer"'),
 ('routes.provider-mode','Provider mode; local and test default to deterministic fake adapters','string',true,'"test"'),
 ('routes.provider-timeout-ms','Bounded provider request timeout','number',true,'15000'),
 ('routes.provider-max-stops','Maximum stops accepted by one optimization request','number',true,'200'),
 ('routes.provider-max-retries','Maximum transient provider retries','number',true,'2'),
 ('routes.provider-max-retry-delay-ms','Maximum accepted provider retry-after delay','number',true,'5000'),
 ('routes.provider-fallback','Safe fallback policy after provider failure','string',true,'"retain-source"') on conflict do nothing;

alter table app_private.route_versions drop constraint route_versions_generation_method_check;
alter table app_private.route_versions add constraint route_versions_generation_method_check check(generation_method in ('deterministic_baseline','provider_optimized'));
alter table app_private.route_versions add column optimization_attempt_id uuid, add column estimate_mode text not null default 'baseline_schematic' check(estimate_mode in ('baseline_schematic','static_road','traffic_aware'));

create table app_private.route_optimization_attempts (
 route_optimization_attempt_id uuid primary key default gen_random_uuid(), route_plan_id uuid not null references app_private.route_plans,
 source_route_version_id uuid not null references app_private.route_versions, candidate_route_version_id uuid references app_private.route_versions,
 service_region_id uuid not null references app_private.service_regions, lifecycle_status text not null default 'pending' check(lifecycle_status in ('pending','running','succeeded','failed','cancelled','superseded','accepted','rejected')),
 routing_provider text not null, optimization_provider text not null, adapter_version text not null, input_signature text not null,
 input_snapshot jsonb not null, candidate_result jsonb, comparison jsonb, provider_warnings jsonb not null default '[]',
 failure_classification text check(failure_classification in ('retryable','rate_limited','authentication','invalid_request','permanent','timeout','invalid_response')),
 failure_summary text, correlation_id uuid not null, requested_by uuid not null references auth.users, requested_at timestamptz not null default now(), started_at timestamptz, completed_at timestamptz, updated_at timestamptz not null default now()
);
alter table app_private.route_versions add constraint route_versions_optimization_attempt_fk foreign key(optimization_attempt_id) references app_private.route_optimization_attempts on delete set null;
create index route_versions_optimization_attempt_idx on app_private.route_versions(optimization_attempt_id) where optimization_attempt_id is not null;
create index route_optimization_attempt_version_idx on app_private.route_optimization_attempts(source_route_version_id,requested_at desc);
create index route_optimization_attempt_region_idx on app_private.route_optimization_attempts(service_region_id,lifecycle_status,requested_at desc);
create index route_optimization_attempt_plan_idx on app_private.route_optimization_attempts(route_plan_id,requested_at desc);
create index route_optimization_attempt_candidate_idx on app_private.route_optimization_attempts(candidate_route_version_id) where candidate_route_version_id is not null;
create index route_optimization_attempt_requester_idx on app_private.route_optimization_attempts(requested_by,requested_at desc);
create table app_private.routing_provider_usage (
 routing_provider_usage_id uuid primary key default gen_random_uuid(), route_optimization_attempt_id uuid references app_private.route_optimization_attempts on delete set null,
 provider_key text not null, capability text not null, request_units integer not null check(request_units>=0), stop_count integer not null check(stop_count>=0),
 outcome text not null check(outcome in ('succeeded','failed','rate_limited','timed_out')), duration_ms integer check(duration_ms>=0), billing_units numeric(12,4), recorded_at timestamptz not null default now()
);
create index routing_usage_provider_time_idx on app_private.routing_provider_usage(provider_key,recorded_at desc);
create index routing_usage_attempt_idx on app_private.routing_provider_usage(route_optimization_attempt_id) where route_optimization_attempt_id is not null;
create table app_private.routing_provider_health (
 provider_key text not null, capability text not null, health_status text not null check(health_status in ('healthy','degraded','unhealthy','disabled','unknown')),
 safe_summary text not null, checked_at timestamptz not null, primary key(provider_key,capability)
);
insert into app_private.routing_provider_health(provider_key,capability,health_status,safe_summary,checked_at) values
 ('fake-routing','routing','healthy','Deterministic fake routing provider is available.',now()),
 ('fake-optimizer','optimization','healthy','Deterministic fake optimization provider is available.',now());
alter table app_private.route_optimization_attempts enable row level security; alter table app_private.routing_provider_usage enable row level security; alter table app_private.routing_provider_health enable row level security;
revoke all on app_private.route_optimization_attempts,app_private.routing_provider_usage,app_private.routing_provider_health from public,anon,authenticated;
grant select,insert,update on app_private.route_optimization_attempts,app_private.routing_provider_usage,app_private.routing_provider_health to service_role;

create or replace function app_private.optimization_input(p_version_id uuid) returns jsonb language sql stable set search_path='' as $$
 select jsonb_build_object('routeVersionId',v.route_version_id,'routePlanId',p.route_plan_id,'serviceRegionId',p.service_region_id,'rosterSignature',v.roster_signature,'deterministicSeed',0,'constraints',v.constraint_snapshot,
 'vehicles',coalesce((select jsonb_agg(jsonb_build_object('routeId',r.planned_route_id,'teamId',r.team_id,'capacityUnits',r.vehicle_capacity_units,'usableWindowMinutes',r.usable_window_minutes,'start',jsonb_build_object('latitude',ds.latitude,'longitude',ds.longitude),'end',jsonb_build_object('latitude',de.latitude,'longitude',de.longitude)) order by r.route_sequence) from app_private.planned_routes r join app_private.depots ds on ds.depot_id=r.start_depot_id join app_private.depots de on de.depot_id=r.end_depot_id where r.route_version_id=v.route_version_id),'[]'),
 'stops',coalesce((select jsonb_agg(jsonb_build_object('stopId',s.planned_route_stop_id,'eligibleRouteIds',(select coalesce(jsonb_agg(r2.planned_route_id order by r2.planned_route_id),'[]') from app_private.planned_routes r2 join app_private.service_configurations sc on sc.service_configuration_id=s.service_configuration_id where r2.route_version_id=v.route_version_id and (sc.default_team_id=r2.team_id or exists(select 1 from app_private.territory_eligible_teams et where et.territory_id=sc.territory_id and et.team_id=r2.team_id))),'point',jsonb_build_object('latitude',s.latitude,'longitude',s.longitude),'capacityUnits',s.drum_units,'serviceDurationMinutes',s.planned_duration_minutes) order by s.planned_route_stop_id) from app_private.planned_route_stops s where s.route_version_id=v.route_version_id),'[]'))
 from app_private.route_versions v join app_private.route_plans p on p.route_plan_id=v.route_plan_id where v.route_version_id=p_version_id $$;

create or replace function api.route_provider_configuration(p_environment_name text) returns jsonb language sql stable security definer set search_path='' as $$
 select coalesce(jsonb_object_agg(d.configuration_key,coalesce(v.configuration_value,d.default_value)),'{}')
 from app_private.configuration_definitions d left join app_private.configuration_values v on v.configuration_key=d.configuration_key and v.environment_name=p_environment_name
 where d.configuration_key like 'routes.provider-%' or d.configuration_key in ('routes.routing-provider','routes.optimization-provider') $$;

create or replace function api.route_optimization_start(p_actor_id uuid,p_source_version_id uuid,p_expected_updated_at timestamptz,p_correlation_id uuid,p_routing_provider text,p_optimization_provider text,p_adapter_version text)
returns jsonb language plpgsql security definer set search_path='' as $$ declare v app_private.route_versions%rowtype;p app_private.route_plans%rowtype;input jsonb;attempt app_private.route_optimization_attempts%rowtype;begin
 select * into v from app_private.route_versions where route_version_id=p_source_version_id for update; select * into p from app_private.route_plans where route_plan_id=v.route_plan_id; if v.route_version_id is null then raise exception 'not found' using errcode='P0002';end if;perform app_private.require_routes_access(p_actor_id,'routes.optimize',p.service_region_id);
 if v.version_status not in ('draft','ready') then raise exception 'new_draft_required' using errcode='55000';end if;if v.updated_at<>p_expected_updated_at then raise exception 'stale_update' using errcode='40001';end if;if app_private.refresh_route_staleness(v.route_version_id) then raise exception 'stale_route_input' using errcode='40001';end if;
 if exists(select 1 from app_private.planned_routes r join app_private.depots ds on ds.depot_id=r.start_depot_id join app_private.depots de on de.depot_id=r.end_depot_id where r.route_version_id=v.route_version_id and (ds.latitude is null or ds.longitude is null or de.latitude is null or de.longitude is null)) then raise exception 'depot_coordinates_required' using errcode='22023';end if;
 input:=app_private.optimization_input(v.route_version_id);insert into app_private.route_optimization_attempts(route_plan_id,source_route_version_id,service_region_id,routing_provider,optimization_provider,adapter_version,input_signature,input_snapshot,correlation_id,requested_by) values(p.route_plan_id,v.route_version_id,p.service_region_id,p_routing_provider,p_optimization_provider,p_adapter_version,md5(input::text),input,p_correlation_id,p_actor_id) returning * into attempt;
 insert into app_private.business_audit_facts(action_key,actor_id,module_key,target_type,target_id,correlation_id,after_state) values('routes.optimization_requested',p_actor_id,'routes','route-optimization-attempt',attempt.route_optimization_attempt_id,p_correlation_id,jsonb_build_object('sourceVersionId',v.route_version_id,'provider',p_optimization_provider));
 insert into app_private.outbox_events(producer_module,event_name,event_version,aggregate_type,aggregate_id,payload,correlation_id,actor_kind,actor_id,occurred_at) values('routes','Routes.RouteOptimizationRequested',1,'route-plan',p.route_plan_id,jsonb_build_object('routePlanId',p.route_plan_id,'attemptId',attempt.route_optimization_attempt_id,'sourceVersionId',v.route_version_id),p_correlation_id,'user',p_actor_id::text,now());return to_jsonb(attempt);end $$;

create or replace function api.route_optimization_get(p_actor_id uuid,p_attempt_id uuid) returns jsonb language plpgsql security definer set search_path='' as $$declare a app_private.route_optimization_attempts%rowtype;begin select * into a from app_private.route_optimization_attempts where route_optimization_attempt_id=p_attempt_id;if a.route_optimization_attempt_id is null then raise exception 'not found' using errcode='P0002';end if;perform app_private.require_routes_access(p_actor_id,'routes.optimization.read',a.service_region_id);return to_jsonb(a);end$$;

create or replace function api.route_optimization_complete(p_actor_id uuid,p_attempt_id uuid,p_result jsonb,p_duration_ms integer,p_correlation_id uuid)
returns jsonb language plpgsql security definer set search_path='' as $$declare a app_private.route_optimization_attempts%rowtype;expected_count integer;result_count integer;assignment_count integer;comparison_result jsonb;begin select * into a from app_private.route_optimization_attempts where route_optimization_attempt_id=p_attempt_id for update;perform app_private.require_routes_access(p_actor_id,'routes.optimize',a.service_region_id);if a.lifecycle_status not in ('pending','running') then raise exception 'attempt_not_pending' using errcode='55000';end if;
 select count(*) into expected_count from app_private.planned_route_stops where route_version_id=a.source_route_version_id;select count(*),count(distinct x.stop_id) into assignment_count,result_count from (select jsonb_array_elements_text(r->'stopIds') stop_id from jsonb_array_elements(coalesce(p_result->'routes','[]')) r union all select jsonb_array_elements_text(coalesce(p_result->'unassignedStopIds','[]')))x;
 if assignment_count<>expected_count or result_count<>expected_count
 or exists(select 1 from jsonb_array_elements(coalesce(p_result->'routes','[]')) result_route where not exists(select 1 from app_private.planned_routes pr where pr.route_version_id=a.source_route_version_id and pr.planned_route_id=(result_route->>'routeId')::uuid))
 or exists(select 1 from (select result_route->>'routeId' route_id,jsonb_array_elements_text(result_route->'stopIds')::uuid stop_id from jsonb_array_elements(coalesce(p_result->'routes','[]')) result_route) q where not exists(select 1 from app_private.planned_route_stops s where s.route_version_id=a.source_route_version_id and s.planned_route_stop_id=q.stop_id))
 or exists(select 1 from (select (result_route->>'routeId')::uuid route_id,jsonb_array_elements_text(result_route->'stopIds')::uuid stop_id from jsonb_array_elements(coalesce(p_result->'routes','[]')) result_route) q join app_private.planned_routes pr on pr.planned_route_id=q.route_id join app_private.planned_route_stops ps on ps.planned_route_stop_id=q.stop_id join app_private.service_configurations sc on sc.service_configuration_id=ps.service_configuration_id where not(sc.default_team_id=pr.team_id or exists(select 1 from app_private.territory_eligible_teams et where et.territory_id=sc.territory_id and et.team_id=pr.team_id)))
 or exists(select 1 from jsonb_array_elements(coalesce(p_result->'routes','[]')) result_route join app_private.planned_routes pr on pr.planned_route_id=(result_route->>'routeId')::uuid where (select coalesce(sum(ps.drum_units),0) from jsonb_array_elements_text(result_route->'stopIds') sid join app_private.planned_route_stops ps on ps.planned_route_stop_id=sid::uuid)>pr.vehicle_capacity_units or (result_route->>'routeDurationMinutes')::integer>pr.usable_window_minutes)
 then raise exception 'invalid_optimizer_response' using errcode='22023';end if;
 comparison_result:=jsonb_build_object('baselineDistanceMetres',coalesce((select sum(planned_distance_metres) from app_private.planned_routes where route_version_id=a.source_route_version_id),0),'candidateDistanceMetres',coalesce((select sum((r->>'travelDistanceMetres')::numeric) from jsonb_array_elements(p_result->'routes')r),0),'baselineDurationMinutes',coalesce((select sum(planned_duration_minutes) from app_private.planned_routes where route_version_id=a.source_route_version_id),0),'candidateDurationMinutes',coalesce((select sum((r->>'routeDurationMinutes')::integer) from jsonb_array_elements(p_result->'routes')r),0),'routeCount',jsonb_array_length(p_result->'routes'),'unassignedCount',jsonb_array_length(coalesce(p_result->'unassignedStopIds','[]')));
 comparison_result:=comparison_result||jsonb_build_object('candidateTravelDurationSeconds',coalesce((select sum((r->>'travelDurationSeconds')::integer) from jsonb_array_elements(p_result->'routes')r),0),'stopCount',expected_count,'totalDrumLoad',coalesce((select sum(drum_units) from app_private.planned_route_stops where route_version_id=a.source_route_version_id),0),'routeDurationSpreadMinutes',coalesce((select max((r->>'routeDurationMinutes')::integer)-min((r->>'routeDurationMinutes')::integer) from jsonb_array_elements(p_result->'routes')r),0));
 update app_private.route_optimization_attempts set lifecycle_status='succeeded',candidate_result=p_result,comparison=comparison_result,provider_warnings=coalesce(p_result->'warnings','[]'),started_at=coalesce(started_at,now()),completed_at=now(),updated_at=now() where route_optimization_attempt_id=p_attempt_id returning * into a;insert into app_private.routing_provider_usage(route_optimization_attempt_id,provider_key,capability,request_units,stop_count,outcome,duration_ms) values(p_attempt_id,a.optimization_provider,'optimization',expected_count,expected_count,'succeeded',p_duration_ms);insert into app_private.business_audit_facts(action_key,actor_id,module_key,target_type,target_id,correlation_id,after_state) values('routes.optimization_succeeded',p_actor_id,'routes','route-optimization-attempt',p_attempt_id,p_correlation_id,jsonb_build_object('candidateDistanceMetres',comparison_result->'candidateDistanceMetres','unassignedCount',comparison_result->'unassignedCount'));return to_jsonb(a);end$$;

create or replace function api.route_optimization_fail(p_actor_id uuid,p_attempt_id uuid,p_classification text,p_summary text,p_duration_ms integer,p_correlation_id uuid) returns jsonb language plpgsql security definer set search_path='' as $$declare a app_private.route_optimization_attempts%rowtype;begin select * into a from app_private.route_optimization_attempts where route_optimization_attempt_id=p_attempt_id for update;perform app_private.require_routes_access(p_actor_id,'routes.optimize',a.service_region_id);update app_private.route_optimization_attempts set lifecycle_status='failed',failure_classification=p_classification,failure_summary=left(p_summary,500),completed_at=now(),updated_at=now() where route_optimization_attempt_id=p_attempt_id returning * into a;insert into app_private.routing_provider_usage(route_optimization_attempt_id,provider_key,capability,request_units,stop_count,outcome,duration_ms) values(p_attempt_id,a.optimization_provider,'optimization',jsonb_array_length(a.input_snapshot->'stops'),jsonb_array_length(a.input_snapshot->'stops'),case when p_classification='rate_limited' then 'rate_limited' when p_classification='timeout' then 'timed_out' else 'failed' end,p_duration_ms);insert into app_private.business_audit_facts(action_key,actor_id,module_key,target_type,target_id,correlation_id,after_state) values('routes.provider_fallback_used',p_actor_id,'routes','route-optimization-attempt',p_attempt_id,p_correlation_id,jsonb_build_object('classification',p_classification,'fallback','retain-source'));return to_jsonb(a);end$$;

create or replace function api.route_optimization_apply(p_actor_id uuid,p_attempt_id uuid,p_expected_source_updated_at timestamptz,p_correlation_id uuid) returns jsonb language plpgsql security definer set search_path='' as $$declare a app_private.route_optimization_attempts%rowtype;source app_private.route_versions%rowtype;newv app_private.route_versions%rowtype;p app_private.route_plans%rowtype;r record;nr uuid;s record;version_no integer;begin select * into a from app_private.route_optimization_attempts where route_optimization_attempt_id=p_attempt_id for update;select * into source from app_private.route_versions where route_version_id=a.source_route_version_id for update;select * into p from app_private.route_plans where route_plan_id=a.route_plan_id for update;perform app_private.require_routes_access(p_actor_id,'routes.optimization.apply',a.service_region_id);if a.lifecycle_status<>'succeeded' then raise exception 'candidate_not_succeeded' using errcode='55000';end if;if source.updated_at<>p_expected_source_updated_at then raise exception 'stale_update' using errcode='40001';end if;select coalesce(max(version_number),0)+1 into version_no from app_private.route_versions where route_plan_id=p.route_plan_id;
 insert into app_private.route_versions(route_plan_id,version_number,source_version_id,generation_method,operational_day_updated_at,roster_signature,constraint_snapshot,planning_metrics,change_reason,created_by,optimization_attempt_id,estimate_mode) values(p.route_plan_id,version_no,source.route_version_id,'provider_optimized',source.operational_day_updated_at,source.roster_signature,source.constraint_snapshot,a.comparison,'Accepted optimized candidate',p_actor_id,p_attempt_id,'static_road') returning * into newv;
 for r in select pr.* from app_private.planned_routes pr where pr.route_version_id=source.route_version_id order by pr.route_sequence loop insert into app_private.planned_routes(route_version_id,daily_roster_entry_id,roster_entry_version,route_sequence,team_id,vehicle_id,staff_snapshot,start_depot_id,end_depot_id,planned_start_at,planned_end_at,usable_window_minutes,vehicle_capacity_units,planned_capacity_units,planned_duration_minutes,planned_distance_metres,constraint_flags) values(newv.route_version_id,r.daily_roster_entry_id,r.roster_entry_version,r.route_sequence,r.team_id,r.vehicle_id,r.staff_snapshot,r.start_depot_id,r.end_depot_id,r.planned_start_at,r.planned_end_at,r.usable_window_minutes,r.vehicle_capacity_units,r.planned_capacity_units,coalesce((select (x->>'routeDurationMinutes')::integer from jsonb_array_elements(a.candidate_result->'routes')x where x->>'routeId'=r.planned_route_id::text),r.planned_duration_minutes),coalesce((select (x->>'travelDistanceMetres')::numeric from jsonb_array_elements(a.candidate_result->'routes')x where x->>'routeId'=r.planned_route_id::text),r.planned_distance_metres),jsonb_build_object('geometry',(select x->'geometry' from jsonb_array_elements(a.candidate_result->'routes')x where x->>'routeId'=r.planned_route_id::text),'strategy','optimized_candidate')) returning planned_route_id into nr;
  for s in select ps.*,q.ordinality seq from jsonb_array_elements(a.candidate_result->'routes')x cross join lateral jsonb_array_elements_text(x->'stopIds') with ordinality q(stop_id,ordinality) join app_private.planned_route_stops ps on ps.planned_route_stop_id=q.stop_id::uuid where x->>'routeId'=r.planned_route_id::text order by q.ordinality loop insert into app_private.planned_route_stops(route_version_id,planned_route_id,sequence_number,client_service_id,service_configuration_id,service_address_id,territory_id,drum_units,latitude,longitude,address_snapshot,service_flags,planned_duration_minutes) values(newv.route_version_id,nr,s.seq,s.client_service_id,s.service_configuration_id,s.service_address_id,s.territory_id,s.drum_units,s.latitude,s.longitude,s.address_snapshot,s.service_flags,s.planned_duration_minutes);end loop;end loop;
 update app_private.route_optimization_attempts set lifecycle_status='accepted',candidate_route_version_id=newv.route_version_id,updated_at=now() where route_optimization_attempt_id=p_attempt_id;update app_private.route_plans set current_version_id=newv.route_version_id,lifecycle_status='draft',updated_at=now() where route_plan_id=p.route_plan_id;insert into app_private.business_audit_facts(action_key,actor_id,module_key,target_type,target_id,correlation_id,after_state) values('routes.optimization_candidate_accepted',p_actor_id,'routes','route-optimization-attempt',p_attempt_id,p_correlation_id,jsonb_build_object('candidateVersionId',newv.route_version_id,'sourceVersionId',source.route_version_id)),('routes.optimized_route_version_created',p_actor_id,'routes','route-version',newv.route_version_id,p_correlation_id,jsonb_build_object('attemptId',p_attempt_id,'sourceVersionId',source.route_version_id));insert into app_private.outbox_events(producer_module,event_name,event_version,aggregate_type,aggregate_id,payload,correlation_id,actor_kind,actor_id,occurred_at) values('routes','Routes.OptimizedRouteVersionCreated',1,'route-plan',p.route_plan_id,jsonb_build_object('routePlanId',p.route_plan_id,'attemptId',p_attempt_id,'sourceVersionId',source.route_version_id,'candidateVersionId',newv.route_version_id),p_correlation_id,'user',p_actor_id::text,now());return app_private.route_version_document(newv.route_version_id);end$$;

create or replace function api.route_optimization_reject(p_actor_id uuid,p_attempt_id uuid,p_reason text,p_correlation_id uuid) returns jsonb language plpgsql security definer set search_path='' as $$declare a app_private.route_optimization_attempts%rowtype;begin select * into a from app_private.route_optimization_attempts where route_optimization_attempt_id=p_attempt_id for update;perform app_private.require_routes_access(p_actor_id,'routes.optimization.apply',a.service_region_id);if a.lifecycle_status<>'succeeded' or nullif(trim(p_reason),'') is null then raise exception 'candidate_not_rejectable' using errcode='22023';end if;update app_private.route_optimization_attempts set lifecycle_status='rejected',updated_at=now() where route_optimization_attempt_id=p_attempt_id returning * into a;insert into app_private.business_audit_facts(action_key,actor_id,module_key,target_type,target_id,correlation_id,after_state) values('routes.optimization_candidate_rejected',p_actor_id,'routes','route-optimization-attempt',p_attempt_id,p_correlation_id,jsonb_build_object('reason',p_reason));return to_jsonb(a);end$$;

create or replace function api.route_provider_health(p_actor_id uuid,p_region_id uuid) returns jsonb language plpgsql security definer set search_path='' as $$begin perform app_private.require_routes_access(p_actor_id,'routes.optimization.read',p_region_id);return coalesce((select jsonb_agg(to_jsonb(h) order by provider_key,capability) from app_private.routing_provider_health h),'[]');end$$;
revoke all on function api.route_provider_configuration(text),api.route_optimization_start(uuid,uuid,timestamptz,uuid,text,text,text),api.route_optimization_get(uuid,uuid),api.route_optimization_complete(uuid,uuid,jsonb,integer,uuid),api.route_optimization_fail(uuid,uuid,text,text,integer,uuid),api.route_optimization_apply(uuid,uuid,timestamptz,uuid),api.route_optimization_reject(uuid,uuid,text,uuid),api.route_provider_health(uuid,uuid) from public,anon,authenticated;
grant execute on function api.route_provider_configuration(text),api.route_optimization_start(uuid,uuid,timestamptz,uuid,text,text,text),api.route_optimization_get(uuid,uuid),api.route_optimization_complete(uuid,uuid,jsonb,integer,uuid),api.route_optimization_fail(uuid,uuid,text,text,integer,uuid),api.route_optimization_apply(uuid,uuid,timestamptz,uuid),api.route_optimization_reject(uuid,uuid,text,uuid),api.route_provider_health(uuid,uuid) to service_role;
